//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prokat.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public int workId { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronim { get; set; }
        public string Email { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string phoneNum { get; set; }
        public int PaspSeria { get; set; }
        public int PaspNum { get; set; }
        public System.DateTime Birthday { get; set; }
        public Nullable<System.DateTime> LastEnter { get; set; }
        public Nullable<int> typeEnterId { get; set; }
        public int GenderId { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual typeEnter typeEnter { get; set; }
        public virtual work work { get; set; }
    }
}
